- type: entity
  name: АК-74
  parent: EFSBaseRifleAk
  id: EFSBaseWeaponAk74
  abstract: true
  description: "Автомат Калашникова калибра 5,45 мм, разработанный в 1970 году конструктором М. Т. Калашниковым как дальнейшее развитие АКМ в связи с переходом Вооруженных Сил на новый боеприпас 5.45x39."
  components:
  - type: ItemSlots
    slots:
      gun_suppressor:
        whitelist:
          tags:
            - EFSAk74Barrel
      gun_receiver:
        whitelist:
          tags:
            - EFSAkReceiver
      gun_stock:
        whitelist:
          tags:
            - EFSAkStock
      gun_forearm:
        whitelist:
          tags:
            - EFSAkForearm
      gun_magazine:
        insertSound: /Audio/GG/Weapons/AK/in.ogg
        ejectSound: /Audio/GG/Weapons/AK/out.ogg
        whitelist:
          tags:
            - EFSMagazineRifle5.45x39
  - type: Gun
    minAngle: 3
    maxAngle: 16
    angleIncrease: 5
    angleDecay: 20
    fireRate: 6.77

- type: entity
  name: АКС-74
  parent: EFSBaseRifleAk
  id: EFSBaseWeaponAks74
  description: "Dev Item"
  abstract: true
  components:
  - type: Sprite
    sprite: GG/Weapons/ak.rsi
  - type: ItemSlots
    slots:
      gun_magazine:
        insertSound: /Audio/GG/Weapons/AK/in.ogg
        ejectSound: /Audio/GG/Weapons/AK/out.ogg
        whitelist:
          tags:
            - EFSMagazineRifle5.45x39
      gun_suppressor:
        whitelist:
          tags:
            - EFSAk74Barrel
      gun_receiver:
        whitelist:
          tags:
            - EFSAkReceiver
      gun_stock:
        whitelist:
          tags:
            - EFSAkStockN
      gun_forearm:
        whitelist:
          tags:
            - EFSAkForearm
  - type: Gun
    minAngle: 3
    maxAngle: 16
    angleIncrease: 5
    angleDecay: 20
    fireRate: 6.77

- type: entity
  name: АК-74Н
  parent: EFSBaseRifleLAk
  id: EFSBaseWeaponAk74N
  abstract: true
  description: "Автомат Калашникова калибра 5,45 мм, разработанный в 1970 году конструктором М. Т. Калашниковым как дальнейшее развитие АКМ в связи с переходом Вооруженных Сил на новый боеприпас 5.45x39. Основное отличие от штатного АК-74 - наличие крепления для оптических и ночных прицелов."
  components:
  - type: Sprite
    sprite: GG/Weapons/akl.rsi
  - type: ItemSlots
    slots:
      gun_magazine:
        insertSound: /Audio/GG/Weapons/AK/in.ogg
        ejectSound: /Audio/GG/Weapons/AK/out.ogg
        whitelist:
          tags:
            - EFSMagazineRifle5.45x39
      gun_suppressor:
        whitelist:
          tags:
            - EFSAk74Barrel
      gun_receiver:
        whitelist:
          tags:
            - EFSAkReceiver
      gun_stock:
        whitelist:
          tags:
            - EFSAkStock
      gun_forearm:
        whitelist:
          tags:
            - EFSAkForearm
      gun_scope:
        priority: 7
        whitelist:
          tags:
            - EFSNScope
  - type: ContainerContainer
    containers:
      gun_scope: !type:ContainerSlot
      gun_chamber: !type:ContainerSlot
  - type: Gun
    minAngle: 3
    maxAngle: 16
    angleIncrease: 4
    angleDecay: 90
    fireRate: 6.77

- type: entity
  name: АК-74Н
  parent: EFSBaseRifleLAk
  id: EFSBaseWeaponAk74M
  abstract: true
  description:
  components:
  - type: Sprite
    sprite: GG/Weapons/akl.rsi
  - type: ItemSlots
    slots:
      gun_magazine:
        insertSound: /Audio/GG/Weapons/AK/in.ogg
        ejectSound: /Audio/GG/Weapons/AK/out.ogg
        whitelist:
          tags:
            - EFSMagazineRifle5.45x39
      gun_suppressor:
        whitelist:
          tags:
            - EFSAk74Barrel
      gun_receiver:
        whitelist:
          tags:
            - EFSAkReceiver
      gun_stock:
        whitelist:
          tags:
            - EFSAkStock
      gun_forearm:
        whitelist:
          tags:
            - EFSAkForearm
      gun_scope:
        priority: 7
        whitelist:
          tags:
            - EFSNScope
  - type: ContainerContainer
    containers:
      gun_scope: !type:ContainerSlot
      gun_chamber: !type:ContainerSlot
  - type: Gun
    minAngle: 3
    maxAngle: 16
    angleIncrease: 4.1
    angleDecay: 90
    fireRate: 7.33

