using Content.Shared.GG.Dialogue;
using Content.Shared.GG.Quests;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using System.Numerics;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Shared.Utility;
using Robust.Client.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Client.Graphics;
using System;

namespace Content.Client.GG.Dialogue
{


    [GenerateTypedNameReferences]
    public sealed partial class DialogueWindow : DefaultWindow
    {
        private readonly Dictionary<string, DialoguePrototype> _dialoguePrototypes = new();
        private readonly SpriteSystem _spriteSystem = default!;

        private readonly DialogueSystem _dialogueSystem = default!;

        float AnswerMargin = 0;

        float DefaultAnswerMargin = 0;

        private List<Button> ButtonsList = new();

        private readonly NetEntity _player;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;
        public DialogueWindow(NetEntity player, NetEntity avatar, DialoguePrototype dialogue)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _player = player;


            Title = "Диалог";

            _spriteSystem = _entityManager.System<SpriteSystem>();
            _dialogueSystem = _entityManager.System<DialogueSystem>();
            RestartBox();
            Messeage.Modulate = Color.White;
            if(_entityManager.GetEntity(avatar) != null)
            {
                var target = _entityManager.GetEntity(avatar);
                TargetName.Text = _entityManager.GetComponent<MetaDataComponent>(target).EntityName;
                SetAvaterIcon(target);
            }

            GenerateDialogue(dialogue.ID);

        }

        public void NextNodeDialogue(string nextId)
        {
            RestartBox();
            GenerateDialogue(nextId);
        }

        public void GenerateDialogue(string nextId)
        {

            var dialogue = _prototypeManager.Index<DialoguePrototype>(nextId);
            if (dialogue == null)
            {
                Logger.Warning($"DialoguePrototype with ID {nextId} not found.");
                return;
            }

            Messeage.Text = dialogue.NarratorText;


            foreach (var response in dialogue.Responses)
            {
                if(!_dialogueSystem.QuestCheckButtons(_player, response))
                    continue;

                var button = new Button
                {
                    HorizontalExpand = false,
                    Name = response.NextDialogueId,
                    Text = response.Text,
                };

                var text = new TextureRect
                {
                    Texture = GetIconTexture(DetermineIconType(response)),
                    TextureScale = new Vector2(1, 1),
                    HorizontalExpand = true,
                    Margin = new Thickness(25, -30, 0, 0),
                };




                if (!string.IsNullOrEmpty(response.QuestId))
                {
                    button.OnPressed += _ =>
                    {
                        _dialogueSystem.QuestGrant(_player, response.QuestId);
                    };
                }

                if (!string.IsNullOrEmpty(response.QuestCompleteId))
                {
                    button.OnPressed += _ =>
                    {
                        _dialogueSystem.QuestComplete(_player, response.QuestCompleteId);
                    };
                }

                button.OnPressed += _ =>
                {
                    if (!string.IsNullOrEmpty(button.Name))
                    {
                        NextNodeDialogue(button.Name);
                    }
                    else
                    {
                        Close();
                    }
                };

                AddButton(button, text);
            }
        }


        public void AddButton(Button button, TextureRect texture)
        {
            button.OnPressed += _ =>
            {
                if (button.Name != null && button.Name != "Dexit")
                {
                    NextNodeDialogue(button.Name);
                }
                else if (button.Name == "Dexit")
                {
                    Close();
                }
            };

            DialogueChoice.AddChild(button);
            DialogueChoice.AddChild(texture);


            var temp = DialogueChoicePanel.Size;
            // temp.Y += 29;
            // AnswerMargin -= 29;
            // DialogueChoice.Margin = new Thickness(0, AnswerMargin, 0, 0);
            DialogueChoicePanel.SetSize = temp;

            ButtonsList.Add(button);
        }

        public void RestartBox()
        {

            DialogueChoice.RemoveAllChildren();

            foreach (var but in ButtonsList)
            {
                but.Dispose();
            }
            ButtonsList.Clear();


            Messeage.SetMessage("");


            AnswerMargin = DefaultAnswerMargin;
            DialogueChoice.Margin = new Thickness(0, -29, 0, 0);
            DialogueChoicePanel.SetSize = new Vector2(350, 29);
        }

        public void SetAvaterIcon(EntityUid uid)
        {
            var query = _entityManager.GetEntityQuery<SpriteComponent>();
            if(query.TryComp(uid, out var sprite) && sprite.BaseRSI != null)
            {
                var state = sprite.LayerGetState(0);
                if(state.Name != null)
                {
                    var AvatarTexture = new SpriteSpecifier.Rsi(sprite.BaseRSI.Path, state.Name);
                    AvatarIcon.Texture = _spriteSystem.Frame0(AvatarTexture);
                }
            }

        }

        private string DetermineIconType(DialogueResponse response)
        {
            if (!string.IsNullOrEmpty(response.QuestId) || !string.IsNullOrEmpty(response.QuestCompleteId))
                return "quest";
            if (!string.IsNullOrEmpty(response.NextDialogueId))
                return "chat";
            return "exit";
        }

        private Texture GetIconTexture(string iconType)
        {
            var query = _entityManager.GetEntityQuery<SpriteComponent>();
            var path = new ResPath("/Textures/GG/Interface/Icons/chat.rsi");
            var iconTexture = new SpriteSpecifier.Rsi(path, iconType);

            if (iconTexture != null)
            {
                return _spriteSystem.Frame0(new SpriteSpecifier.Rsi(path, iconType));
            }

            // Возвращаем пустую текстуру, если иконка не найдена
            return Texture.White;
        }



    }
}


