
# - type: department
#   id: Civilian
#   description: department-Civilian-description
#   color: "#9FED58"
#   weight: -10
#   roles:
#   - Passenger
#   - USEC

- type: department
  id: Security
  description: Постарайтесь выжить
  color: "#DE3A3A"
  roles:
  - Passenger
  - USEC
